Moved login to homepage
carsondrobe/Fellas pull request #102
Opened 2024-03-07 04:11 UTC by cmcahoon01

Now toggles alerts and submit feedback when logged in

2024-03-07 04:21 UTC, cmcahoon01 commented
![Animation2](https://github.com/carsondrobe/Fellas/assets/31668119/66cde0da-d995-449e-8337-5e62f1a3afdf)

2024-03-07 22:13 UTC, abijeet-dhillon approved these changes, later dismissed
I created a test user and it worked for me, great job! Just need to fix the merge conflicts.

2024-03-07 22:31 UTC, abijeet-dhillon requested changes
I created a test user and it worked for me, great job! Just need to fix the merge conflicts.

2024-03-08 01:14 UTC, robertyac commented on Site/bc_weather_station_dashboard/website/templates/home.html
> +        {% if error %}
whoops didn't mean to make a suggestion just wanted to highlight that, did that in vscode so thats why. mb

2024-03-08 01:17 UTC, cmcahoon01 commented on Site/bc_weather_station_dashboard/website/templates/home.html
> +        {% if error %}
I'm not sure. My IDE doesn't say anything, but if yours has a suggestion feel free

2024-03-08 01:18 UTC, robertyac requested changes
Looks good and works as intended for me!!

One thing, we may want to add a field in the register user that they can choose a user name. Just so we can then display their username in the nav bar in the top right corner instead of a profile picture, and perhaps when they click that the dropdown still appears? 

 since right now user name is defaulted to their email:
![Screenshot 2024-03-07 at 5 13 02 PM](https://github.com/carsondrobe/Fellas/assets/112982183/f5b6ee65-36d7-4d58-9bb0-153605753e2d)

LMK what you think

2024-03-08 01:22 UTC, cmcahoon01 commented
Yeah, I thought about that and decided I wished I had a manager or design specialist to decide for me. It would be a trivial change, but it would make registration a bit bulkier so I left it at just username for now. Other thoughts?

2024-03-08 01:25 UTC, robertyac commented
Yeah that's fair, I just thought it would be good for users to create their own username since we could use that instead of a profile image but it's not a huge deal just depends what everyone thinks

2024-03-08 21:00 UTC, carsondrobe commented
Works, will need to make an issue to link this user to their Feedback

2024-03-08 21:00 UTC, carsondrobe approved these changes
LGTM, will add an issue for linking these Users to Feedback View

2024-03-08 21:13 UTC, abijeet-dhillon approved these changes
Works correctly for me, great job!

2024-03-08 22:15 UTC, robertyac approved these changes

2024-03-08 22:17 UTC, robertyac requested changes
Add username field (I take back my approval)

2024-03-08 22:35 UTC, robertyac approved these changes

2024-03-08 22:35 UTC, robertyac commented
Works well, tested it out. nice work

2024-03-08 22:35 UTC, merged