Login HTML
carsondrobe/Fellas pull request #49
Opened 2024-02-23 19:07 UTC by Davis245

Here is the HTML and CSS for the login page.

2024-02-24 07:16 UTC, robertyac commented
Looks good to me. We may be using bootstrap though we'll have to decide as a group for now it's good. Also- .pyc files don't need to be committed they should just be ignored.

2024-02-24 07:18 UTC, robertyac requested changes
Looks good for the initial go. We may be using bootstrap though going forward I think Carson mentioned?  We'll have to decide as a group. 

 .pyc files don't need to be committed they should just be ignored.

2024-02-24 07:27 UTC, robertyac approved these changes

2024-02-25 01:39 UTC, carsondrobe commented
Consider moving the CSS <style></style> section to an external login.css stylesheet and linking it to the login.html. This is best practice.

2024-02-28 03:43 UTC, closed without merging