Implemented map with functionality for the left column.
carsondrobe/Fellas pull request #72
Opened 2024-02-29 09:10 UTC by abijeet-dhillon

Implemented the map with the following functionality:
- scrollable and moveable map
- map populated with all of the weather stations in our data
- ability to click on markers (fire station icons) and view weather station information in a pop up
- on start up, the map opens with a focus around aspen grove weather station (id = 100), opens the pop up for that station, and displays the station id and name in the html element above the map with its lat., long., and elevation in the html elements below

Testing for the map is found in the map.test.js file in the leaflet folder (will move to the testing folder in later commits).

2024-02-29 19:16 UTC, robertyac requested changes
Im getting some errors when I'm trying to run it on the server. See attached images:

<img width="877" alt="Screenshot 2024-02-29 at 11 12 34 AM" src="https://github.com/carsondrobe/Fellas/assets/112982183/8d80b65b-6c8a-4954-9edc-1355b8eea2e1">
<img width="1080" alt="Screenshot 2024-02-29 at 11 12 05 AM" src="https://github.com/carsondrobe/Fellas/assets/112982183/356ab69f-b8a3-43e6-bb14-3bd15fb34a18">

2024-02-29 19:16 UTC, robertyac commented on Site/bc_weather_station_dashboard/website/leaflet/leaflet-src.esm.js
This shouldn't be uploaded to the GitHub, add to dependancies .txt file.

2024-02-29 22:02 UTC, carsondrobe commented on Site/bc_weather_station_dashboard/website/leaflet/leaflet-src.esm.js
run `pip freeze > requirements.txt`

2024-03-01 04:41 UTC, robertyac commented
I still think leaflet is being uploaded with this pull request, I don't know if you are working on it still but I'm just going through the PR right now.

2024-03-01 05:16 UTC, abijeet-dhillon commented
Just fixed it. I scrapped the idea of getting the data from the csv and instead am pulling the data for the map directly from the database. Give it a try, it should be working on the server smoothly now.

2024-03-01 05:35 UTC, robertyac approved these changes
Awesome! Looks great I really like the icons and it's great you got the info from the database instead of the csv. 

I went ahead and deleted the copy you had in static, we still have one in `Site/bc_weather_station_dashboard/website/data` 

Other than that LGTM, for future issues if you're still interested in the map you can maybe see if there is an "easy" way to get the users location and set the default station to the closest one as we discussed with Rohit.

2024-03-01 20:47 UTC, Davis245 approved these changes
Great functionality, well done!

2024-03-01 20:56 UTC, merged