81 ffmc UI
carsondrobe/Fellas pull request #97
Opened 2024-03-07 01:23 UTC by Davis245

Created the ffmc visualization using html, css, and javaScript:
      - The html is on the fire.html in the ffmc widget spot
      - The css is in static/css/ffmc.css
      - The javaScript is in static/JavaScript/ffmc.js
      
The functionality can you tested by manipulating the example value in the ffmc.js file.

2024-03-07 03:58 UTC, robertyac commented
I can't get onto the page since home doesn't exist now. I tried all your other pull requests too and @cmcahoon01 's PR and I get the same thing. Looks like the settings or urls files need to be updated.

![Screenshot 2024-03-06 at 7 55 13 PM](https://github.com/carsondrobe/Fellas/assets/112982183/8daf5472-a1be-44f6-bd3f-51b4a968188e)

2024-03-07 04:01 UTC, cmcahoon01 commented
I've just been struggling through the same issue. All references to "home" in views.py need to be replaced with weather or fire

2024-03-08 20:50 UTC, carsondrobe requested changes

2024-03-08 20:50 UTC, carsondrobe commented on Site/bc_weather_station_dashboard/website/views.py
>      return render(request, "home.html", {})
Change this to "weather.html"

2024-03-08 20:50 UTC, carsondrobe commented on Site/bc_weather_station_dashboard/website/views.py
>      return render(request, "home.html", {})
return render(request, "weather.html", {})

2024-03-08 21:14 UTC, carsondrobe approved these changes
WORKS

2024-03-08 21:33 UTC, robertyac approved these changes
lgtm

2024-03-08 21:33 UTC, merged